# Adding two vectors in TensorFlow

$\begin{bmatrix} 1. & 1. & 1. & 1.\end{bmatrix} + \begin{bmatrix} 2. & 2. & 2. & 2.\end{bmatrix} = \begin{bmatrix} 3. & 3. & 3. & 3.\end{bmatrix}$

In [2]:
from __future__ import print_function
import numpy as np
import tensorflow as tf

with tf.Session():
    input1 = tf.constant([1.0, 1.0, 1.0, 1.0])
    input2 = tf.constant([2.0, 2.0, 2.0, 2.0])
    output = tf.add(input1, input2)
    result = output.eval()
    print("result: ", result)

result:  [3. 3. 3. 3.]


In [3]:
print([x + y for x, y in zip([1.0] * 4, [2.0] * 4)])

[3.0, 3.0, 3.0, 3.0]


In [4]:
x, y = np.full(4, 1.0), np.full(4, 2.0)
print("{} + {} = {}".format(x, y, x + y))

[1. 1. 1. 1.] + [2. 2. 2. 2.] = [3. 3. 3. 3.]


# Multiple operations

In [5]:
with tf.Session():
    input1 = tf.constant(1.0, shape=[4])
    input2 = tf.constant(2.0, shape=[4])
    input3 = tf.constant(3.0, shape=[4])
    output = tf.add(tf.add(input1, input2), input3)
    result = output.eval()
    print(result)

[6. 6. 6. 6.]


In [6]:
with tf.Session():
    input1 = tf.constant(1.0, shape=[4])
    input2 = tf.constant(2.0, shape=[4])
    output = input1 + input2
    print(output.eval())

[3. 3. 3. 3.]


##  Adding two matrices

Next, let's do something very similar, adding two matrices:

$\begin{bmatrix}
  1. & 1. & 1. \\
  1. & 1. & 1. \\
\end{bmatrix} + 
\begin{bmatrix}
  1. & 2. & 3. \\
  4. & 5. & 6. \\
\end{bmatrix} = 
\begin{bmatrix}
  2. & 3. & 4. \\
  5. & 6. & 7. \\
\end{bmatrix}$

In [7]:
import tensorflow as tf
import numpy as np

with tf.Session():
    input1 = tf.constant(1.0, shape=[2, 3])
    input2 = tf.constant(np.reshape(np.arange(1.0, 7.0, dtype=np.float32), (2, 3)))
    output = tf.add(input1, input2)
    print(output.eval())

[[2. 3. 4.]
 [5. 6. 7.]]


##  Multiplying matrices

In [8]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np

with tf.Session():
    input_features = tf.constant(np.reshape([1, 0, 0, 1], (1, 4)).astype(np.float32))
    weights = tf.constant(np.random.randn(4, 2).astype(np.float32))
    output = tf.matmul(input_features, weights)
    print("Input:")
    print(input_features.eval())
    print("Weights:")
    print(weights.eval())
    print("Output:")
    print(output.eval())

Input:
[[1. 0. 0. 1.]]
Weights:
[[-0.7734664  -0.43657234]
 [-0.18929273  1.3843931 ]
 [-1.0431726  -2.0111153 ]
 [ 1.5415266  -0.05532486]]
Output:
[[ 0.76806015 -0.4918972 ]]


## Use of variables

In [9]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np

with tf.Session() as sess:
    # Set up two variables, total and weights, that we'll change repeatedly.
    total = tf.Variable(tf.zeros([1, 2]))
    weights = tf.Variable(tf.random_uniform([1,2]))

    # Initialize the variables we defined above.
    tf.global_variables_initializer().run()

    # This only adds the operators to the graph right now. The assignment
    # and addition operations are not performed yet.
    update_weights = tf.assign(weights, tf.random_uniform([1, 2], -1.0, 1.0))
    update_total = tf.assign(total, tf.add(total, weights))
  
    for _ in range(5):
        # Actually run the operation graph, so randomly generate weights and then
        # add them into the total. Order does matter here. We need to update
        # the weights before updating the total.
        sess.run(update_weights)
        sess.run(update_total)
    
        print(weights.eval(), total.eval())

[[ 0.03686857 -0.8688512 ]] [[ 0.03686857 -0.8688512 ]]
[[-0.46780944  0.8236575 ]] [[-0.43094087 -0.04519367]]
[[-0.48348498  0.6514585 ]] [[-0.91442585  0.6062648 ]]
[[-0.3094089 -0.6414125]] [[-1.2238348  -0.03514767]]
[[0.9410238 0.4747696]] [[-0.28281093  0.43962193]]
